# Generated by Django 6.1 on 2026-09-02 03:42

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='short_description',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='short_description',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=CKEditor5Field(blank=True, help_text='Full description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=CKEditor5Field(blank=True, help_text='Short description for summary cards'),
        ),
    ]
