# Generated by Django 5.1.13 on 2026-09-03 09:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_casestudy_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enable/Disable')),
                ('url_key', models.SlugField(blank=True, max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_keywords', models.TextField(blank=True)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Expertise Area',
                'verbose_name_plural': 'Expertise Areas',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExpertiseCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('expertise_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='cms.expertisearea')),
            ],
            options={
                'verbose_name': 'Expertise Capability',
                'verbose_name_plural': 'Expertise Capabilities',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
