# Generated by Django 5.1.13 on 2026-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contactinformation_expertisearea_navigationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_title',
            field=models.CharField(blank=True, help_text='Falls back to meta title when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/'),
        ),
        migrations.AddField(
            model_name='expertisearea',
            name='og_title',
            field=models.CharField(blank=True, help_text='Falls back to meta title when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_title',
            field=models.CharField(blank=True, help_text='Falls back to meta title when blank.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og/'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_title',
            field=models.CharField(blank=True, help_text='Falls back to meta title when blank.', max_length=255),
        ),
    ]
