# Generated by Django 5.1.13 on 2026-09-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_casestudy_og_image_casestudy_og_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
