# Generated by Django 5.1.13 on 2026-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_delete_menu_delete_section_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinformation',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='placement',
            field=models.CharField(choices=[('header', 'Header only'), ('footer', 'Footer only'), ('both', 'Header & footer')], default='header', max_length=10),
        ),
    ]
