# Generated by Django 5.1.13 on 2026-09-05 13:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_partnerlogo_processstep_teammember_valuecard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='approach',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Our approach'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='The challenge'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='outcome',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='The outcome'),
        ),
    ]
